#!/usr/bin/env node
/**
 * Real-browser check of the pixel-art agents (frontend/agentes/, generated by
 * tools/agentes/export.py) against the running stack.
 *
 * Proves, in a real Chromium:
 *   - the empty-dashboard scene renders and animates with steps(), in the light and
 *     dark themes, on desktop and at 390 / 360 px, with no horizontal scroll and no
 *     console errors;
 *   - the topbar pause button pauses, survives a reload and resumes;
 *   - prefers-reduced-motion stops the animation and hides the pause button;
 *   - the topbar chip and the Perfil bust are drawn for each role (owner for real;
 *     admin/viewer by rewriting the /auth/me response);
 *   - the connectors widget shows the module's head once the account has a store.
 *
 * Prerequisites (local/manual, NOT wired into CI):
 *   - the docker-compose stack running, frontend on FRONTEND_URL (default
 *     http://localhost:3000) and the API on the same host, port 8000 — that is where
 *     frontend/app.js looks for it.
 *
 * Run: npm install && npm run test:agents   (from this e2e/ directory)
 *   FRONTEND_URL=http://172.x.x.x:3000 npm run test:agents   # e.g. the WSL2 address
 *   SHOTS_DIR=./shots npm run test:agents                    # also save screenshots
 *
 * Each run registers a throwaway account ("Agentes QA") and creates one store in it,
 * so it leaves that test data in the dev database.
 */
const { chromium } = require("playwright");
const fs = require("fs");
const path = require("path");

const FRONTEND_URL = process.env.FRONTEND_URL || "http://localhost:3000";
const API_URL = process.env.API_URL || `${new URL(FRONTEND_URL).protocol}//${new URL(FRONTEND_URL).hostname}:8000`;
const APP = `${FRONTEND_URL.replace(/\/$/, "")}/index.html`;
const SHOTS_DIR = process.env.SHOTS_DIR ? path.resolve(process.env.SHOTS_DIR) : null;
if (SHOTS_DIR) fs.mkdirSync(SHOTS_DIR, { recursive: true });

// Sprite outline color (role "K") per theme: agentes/paleta.css.
const OUTLINE = { light: "rgb(12, 23, 48)", dark: "rgb(5, 10, 23)" };
const VIEWPORTS = { desktop: { width: 1280, height: 800 }, m390: { width: 390, height: 780 }, m360: { width: 360, height: 740 } };

// Go to a sidebar view. Below 860 px the sidebar is an off-canvas drawer, so open it first.
async function goTo(page, navSelector) {
  if (await page.isVisible("#sidebar-toggle")) await page.click("#sidebar-toggle");
  await page.click(navSelector);
}

// Module scenes beyond the connectors one: how to reach each and where it is drawn. A scene is
// only downloaded once its surface is shown (agentes.js paints on un-hide), which is checked too.
const MODULE_SURFACES = [
  { name: "alertas", open: (page) => page.click("#alerts-btn"), host: "#alert-preferences-modal", card: ".modal-card" },
  { name: "reportes", open: (page) => page.click("#reports-btn"), host: "#report-preferences-modal", card: ".modal-card" },
  {
    name: "equipo", open: (page) => goTo(page, "#nav-members"), host: "#members-panel", card: ".store-panel-header",
    extra: async (page, tag) => {
      const drawn = (selector) => page.waitForSelector(selector, { timeout: 10000 }).then(() => true, () => false);
      check(`[${tag}] member rows carry their role chip`, await drawn("#members-list .member-chip svg"));
      const rows = await page.evaluate(() => ({
        rows: document.querySelectorAll("#members-list .member-row").length,
        chips: document.querySelectorAll("#members-list .member-chip svg").length,
        first: (document.querySelector("#members-list .member-chip") || { dataset: {} }).dataset.agentKey || "",
      }));
      check(`[${tag}] one chip per member, owner drawn as owner`, rows.rows > 0 && rows.rows === rows.chips && rows.first.startsWith("chips:owner:"), JSON.stringify(rows));
      await goTo(page, "#nav-profile");
      check(`[${tag}] Perfil's team summary shows role chips`, await drawn("#profile-team-summary .team-chip svg"));
    },
  },
];

const problems = [];
let total = 0;
function check(name, ok, detail = "") {
  total += 1;
  if (!ok) problems.push(`${name} ${detail}`);
  console.log(`${ok ? "PASS" : "FAIL"}  ${name}${detail ? "  — " + detail : ""}`);
}

async function post(url, body, token) {
  const res = await fetch(API_URL + url, {
    method: "POST",
    headers: { "Content-Type": "application/json", ...(token ? { Authorization: `Bearer ${token}` } : {}) },
    body: JSON.stringify(body),
  });
  if (!res.ok) throw new Error(`POST ${url} -> ${res.status} ${await res.text()}`);
  return res.json();
}

async function open(browser, { theme, viewport, tokens, reducedMotion, role }) {
  // Service workers stay blocked so a cached shell from an earlier run can't hide a regression.
  const context = await browser.newContext({ viewport, reducedMotion: reducedMotion || "no-preference", serviceWorkers: "block" });
  await context.addInitScript(({ theme, tokens }) => {
    localStorage.setItem("aramal_theme", theme);
    localStorage.setItem("escal_token", tokens.access_token);
    localStorage.setItem("escal_refresh_token", tokens.refresh_token);
  }, { theme, tokens });
  const page = await context.newPage();
  const errors = [];
  page.on("pageerror", (e) => errors.push(`pageerror: ${e.message}`));
  page.on("console", (m) => { if (m.type() === "error") errors.push(`console: ${m.text()}`); });
  const files = [];
  page.on("response", (r) => { if (r.url().includes("/agentes/")) files.push({ name: r.url().split("/agentes/")[1], status: r.status() }); });
  if (role) {
    await page.route("**/auth/me", async (route) => {
      const res = await route.fetch();
      await route.fulfill({ response: res, json: { ...(await res.json()), role } });
    });
  }
  return { context, page, errors, files };
}

async function shot(page, name, options = {}) {
  if (SHOTS_DIR) await page.screenshot({ path: path.join(SHOTS_DIR, name), ...options });
}

(async () => {
  const browser = await chromium.launch();
  const account = { account_name: "Agentes QA", email: `agentes-qa-${Date.now()}@example.com`, password: "Aramal-QA-2026!xQ7" };
  const tokens = await post("/auth/register", account);
  console.log(`Registered ${account.email} on ${API_URL}`);

  // 1) Empty dashboard scene: both themes, every viewport.
  for (const theme of ["light", "dark"]) {
    for (const [vp, viewport] of Object.entries(VIEWPORTS)) {
      const { context, page, errors, files } = await open(browser, { theme, viewport, tokens });
      await page.goto(APP);
      await page.waitForSelector("#empty-state:not([hidden]) .pxa-scene svg", { timeout: 10000 });
      await page.waitForSelector("#account-chip svg", { timeout: 10000 });
      const m = await page.evaluate(() => {
        const scene = document.querySelector("#empty-state .pxa-scene");
        const strip = getComputedStyle(scene.querySelector(".pxa-st"));
        const box = scene.getBoundingClientRect();
        return {
          name: strip.animationName, timing: strip.animationTimingFunction,
          w: box.width, h: box.height,
          scrollW: document.documentElement.scrollWidth, innerW: window.innerWidth,
          outline: getComputedStyle(scene.querySelector("path.c75")).fill,
        };
      });
      const tag = `${theme}/${vp}`;
      check(`[${tag}] scene animates with steps()`, m.name === "pxa-strip" && m.timing.startsWith("steps(4"), `${m.name} ${m.timing}`);
      check(`[${tag}] no horizontal scroll`, m.scrollW <= m.innerW, `${m.scrollW}/${m.innerW}`);
      check(`[${tag}] scene keeps its 48:30 ratio`, Math.abs(m.w / m.h - 1.6) < 0.02, `${Math.round(m.w)}x${Math.round(m.h)}`);
      check(`[${tag}] theme colors applied`, m.outline === OUTLINE[theme], m.outline);
      check(`[${tag}] no console errors`, errors.length === 0, errors.join(" | "));
      if (vp === "desktop") {
        check(`[${tag}] agent files all load`, files.length > 0 && files.every((f) => f.status === 200), files.map((f) => f.name).join(", "));
      }
      await shot(page, `empty-${theme}-${vp}.png`);
      await context.close();
    }
  }

  // 2) Pause button.
  {
    const { context, page } = await open(browser, { theme: "light", viewport: VIEWPORTS.desktop, tokens });
    await page.goto(APP);
    await page.waitForSelector("#empty-state .pxa-st");
    const read = () => page.evaluate(() => ({
      play: getComputedStyle(document.querySelector("#empty-state .pxa-st")).animationPlayState,
      pressed: document.getElementById("agents-pause").getAttribute("aria-pressed"),
      stored: localStorage.getItem("aramal_agents_paused"),
    }));
    let s = await read();
    check("pause: starts running", s.play === "running" && s.pressed === "false", JSON.stringify(s));
    await page.click("#agents-pause");
    s = await read();
    check("pause: click pauses", s.play === "paused" && s.pressed === "true" && s.stored === "1", JSON.stringify(s));
    await page.reload();
    await page.waitForSelector("#empty-state .pxa-st");
    s = await read();
    check("pause: survives a reload", s.play === "paused" && s.pressed === "true", JSON.stringify(s));
    await page.click("#agents-pause");
    s = await read();
    check("pause: click resumes", s.play === "running" && s.pressed === "false" && s.stored === "0", JSON.stringify(s));
    await context.close();
  }

  // 3) prefers-reduced-motion.
  {
    const { context, page } = await open(browser, { theme: "light", viewport: VIEWPORTS.desktop, tokens, reducedMotion: "reduce" });
    await page.goto(APP);
    await page.waitForSelector("#empty-state .pxa-st");
    const r = await page.evaluate(() => {
      const strip = getComputedStyle(document.querySelector("#empty-state .pxa-st"));
      return { animation: strip.animationName, transform: strip.transform, pause: getComputedStyle(document.getElementById("agents-pause")).display };
    });
    check("reduced motion: animation off", r.animation === "none", r.animation);
    check("reduced motion: first frame stays (no transform)", r.transform === "none", r.transform);
    check("reduced motion: pause button hidden", r.pause === "none", r.pause);
    await context.close();
  }

  // 4) Role portraits: chip in the topbar and bust in Perfil.
  for (const role of ["owner", "admin", "viewer"]) {
    for (const theme of ["light", "dark"]) {
      const { context, page, errors } = await open(browser, { theme, viewport: VIEWPORTS.desktop, tokens, role: role === "owner" ? null : role });
      await page.goto(APP);
      await page.waitForSelector("#account-chip svg");
      await page.click("#nav-profile");
      await page.waitForSelector("#profile-bust svg");
      const keys = await page.evaluate(() => ({
        chip: document.getElementById("account-chip").dataset.agentKey,
        bust: document.getElementById("profile-bust").dataset.agentKey,
      }));
      check(`[${role}/${theme}] chip and bust match the role`, keys.chip.startsWith(`chips:${role}:`) && keys.bust.startsWith(`busts:${role}:`), `${keys.chip} | ${keys.bust}`);
      check(`[${role}/${theme}] no console errors`, errors.length === 0, errors.join(" | "));
      await shot(page, `perfil-${role}-${theme}.png`, { clip: { x: 0, y: 0, width: 1280, height: 330 } });
      await context.close();
    }
  }

  // 5) With a store, the connectors widget carries the module head.
  await post("/stores", { name: "Tienda QA", platform: "shopify", currency: "ARS" }, tokens.access_token);
  for (const theme of ["light", "dark"]) {
    const { context, page, errors } = await open(browser, { theme, viewport: VIEWPORTS.desktop, tokens });
    await page.goto(APP);
    await page.waitForSelector("[data-agent-head] svg", { timeout: 10000 }).catch(() => {});
    check(`[store/${theme}] connectors widget head drawn`, await page.evaluate(() => !!document.querySelector("[data-agent-head] svg")));
    check(`[store/${theme}] empty state hidden`, await page.evaluate(() => document.getElementById("empty-state").hidden));
    check(`[store/${theme}] no console errors`, errors.length === 0, errors.join(" | "));
    await shot(page, `store-${theme}.png`);
    await context.close();
  }

  // 5b) Module scenes: lazy, animated, themed, and inside their container on desktop and at 360 px.
  for (const surface of MODULE_SURFACES) {
    for (const theme of ["light", "dark"]) {
      for (const vp of ["desktop", "m360"]) {
        const { context, page, errors, files } = await open(browser, { theme, viewport: VIEWPORTS[vp], tokens });
        await page.goto(APP);
        await page.waitForSelector("#store-panel:not([hidden])", { timeout: 10000 });
        const tag = `${surface.name}/${theme}/${vp}`;
        const file = `escenas/${surface.name}.json`;
        check(`[${tag}] scene is not downloaded before it is shown`, !files.some((f) => f.name === file), files.map((f) => f.name).join(", "));
        await surface.open(page);
        await page.waitForSelector(`${surface.host} .pxa-scene svg`, { timeout: 10000 });
        const m = await page.evaluate(({ host, card }) => {
          const scene = document.querySelector(`${host} .pxa-scene`);
          const strip = getComputedStyle(scene.querySelector(".pxa-st"));
          const box = scene.getBoundingClientRect();
          const cardBox = document.querySelector(`${host} ${card || ""}`).getBoundingClientRect();
          return {
            name: strip.animationName, timing: strip.animationTimingFunction, playing: strip.animationPlayState,
            inside: box.left >= cardBox.left - 0.5 && box.right <= cardBox.right + 0.5 && box.width > 40 && box.height > 20,
            scrollW: document.documentElement.scrollWidth, innerW: window.innerWidth,
            outline: getComputedStyle(scene.querySelector("path.c75")).fill,
          };
        }, { host: surface.host, card: surface.card });
        check(`[${tag}] scene animates with steps()`, m.name === "pxa-strip" && /^steps\(\d/.test(m.timing) && m.playing === "running", `${m.name} ${m.timing} ${m.playing}`);
        check(`[${tag}] scene sits inside its container`, m.inside);
        check(`[${tag}] no horizontal scroll`, m.scrollW <= m.innerW, `${m.scrollW}/${m.innerW}`);
        check(`[${tag}] theme colors applied`, m.outline === OUTLINE[theme], m.outline);
        await shot(page, `module-${surface.name}-${theme}-${vp}.png`);
        if (surface.extra) await surface.extra(page, tag);
        check(`[${tag}] no console errors`, errors.length === 0, errors.join(" | "));
        await context.close();
      }
    }
  }

  // 6) Store role: GET /stores carries the effective role, and the topbar chip follows it on
  // the Dashboard while Equipo/Perfil keep showing the account role. There is no second
  // user to hold a real per-store override here, so the list response is rewritten.
  {
    const listed = await (await fetch(`${API_URL}/stores`, { headers: { Authorization: `Bearer ${tokens.access_token}` } })).json();
    check("API: GET /stores includes effective_role", listed.length > 0 && listed.every((s) => s.effective_role === "owner"), JSON.stringify(listed.map((s) => s.effective_role)));

    const { context, page, errors } = await open(browser, { theme: "light", viewport: VIEWPORTS.desktop, tokens });
    await page.route("**/stores", async (route) => {
      const res = await route.fetch();
      await route.fulfill({ response: res, json: (await res.json()).map((s) => ({ ...s, effective_role: "viewer" })) });
    });
    const chipIs = (role) => page.waitForFunction(
      (r) => (document.getElementById("account-chip").dataset.agentKey || "").startsWith(`chips:${r}:`), role, { timeout: 8000 },
    ).then(() => true, () => false);
    await page.goto(APP);
    check("store role: chip on the Dashboard shows the store role", await chipIs("viewer"));
    await page.click("#nav-profile");
    check("store role: chip in Perfil shows the account role", await chipIs("owner"));
    await page.click("#nav-dashboard");
    check("store role: chip is back to the store role on the Dashboard", await chipIs("viewer"));
    check("store role: no console errors", errors.length === 0, errors.join(" | "));
    await context.close();
  }

  await browser.close();
  console.log(`\n${total - problems.length}/${total} checks passed`);
  if (problems.length) {
    console.log(`PROBLEMS:\n- ${problems.join("\n- ")}`);
    process.exit(1);
  }
})().catch((err) => {
  console.error(err);
  process.exit(2);
});
