#!/usr/bin/env node
/**
 * Real-browser check of the pixel-art agents (frontend/agentes/, generated by
 * tools/agentes/export.py) against the running stack.
 *
 * Proves, in a real Chromium:
 *   - the empty-dashboard scene renders and animates with steps(), in the light and
 *     dark themes, on desktop and at 390 / 360 px, with no horizontal scroll and no
 *     console errors;
 *   - the topbar pause button pauses, survives a reload and resumes;
 *   - prefers-reduced-motion stops the animation and hides the pause button;
 *   - the topbar chip and the Perfil bust are drawn for each role (owner for real;
 *     admin/viewer by rewriting the /auth/me response);
 *   - the connectors widget shows the module's head once the account has a store;
 *   - every other module's scene (see MODULE_SURFACES) is only downloaded once its modal or
 *     view is shown, animates, sits inside its container, and fits at 360 px in both themes;
 *   - Equipo's member rows and Perfil's team summary show one role chip per person;
 *   - GET /stores carries the effective role and the topbar chip follows it;
 *   - the login welcome agent: invites a first visit to register, covers its eyes on the password,
 *     shakes its head on a failure, follows the password strength while registering, celebrates a
 *     new account, and worries on an expired session;
 *   - the app mascot: an error toast instead of alert(), a loading block while the numbers load,
 *     and the True ROAS card mood against the minimum set in Alertas;
 *   - the first-steps card: shown to owner/admin of a store, ticks off as things get done, and each
 *     button goes straight to its action (no other button is pressed for the person).
 *
 * Prerequisites (local/manual, NOT wired into CI):
 *   - the docker-compose stack running, frontend on FRONTEND_URL (default
 *     http://localhost:3100) and the API on the same host, port 8100 — that is where
 *     frontend/app.js looks for it.
 *
 * Run: npm install && npm run test:agents   (from this e2e/ directory)
 *   FRONTEND_URL=http://172.x.x.x:3100 npm run test:agents   # e.g. the WSL2 address
 *   SHOTS_DIR=./shots npm run test:agents                    # also save screenshots
 *
 * Each run registers a throwaway account ("Agentes QA") and creates one store in it,
 * so it leaves that test data in the dev database.
 */
const { chromium } = require("playwright");
const fs = require("fs");
const path = require("path");

const FRONTEND_URL = process.env.FRONTEND_URL || "http://localhost:3100";
const API_URL = process.env.API_URL || `${new URL(FRONTEND_URL).protocol}//${new URL(FRONTEND_URL).hostname}:8100`;
const APP = `${FRONTEND_URL.replace(/\/$/, "")}/index.html`;
const SHOTS_DIR = process.env.SHOTS_DIR ? path.resolve(process.env.SHOTS_DIR) : null;
if (SHOTS_DIR) fs.mkdirSync(SHOTS_DIR, { recursive: true });

// Sprite outline color (role "K") per theme: agentes/paleta.css.
const OUTLINE = { light: "rgb(12, 23, 48)", dark: "rgb(5, 10, 23)" };
// The stripe of Ross's message boxes (--ross-* in agentes/agentes.css) per theme: greeting, error, and True ROAS
// above / below the minimum (light tones are darker so they hold 3:1 on white).
const STRIPE = {
  light: { neutral: "rgb(59, 140, 184)", error: "rgb(250, 7, 21)", ok: "rgb(8, 135, 111)", warn: "rgb(168, 122, 0)" },
  dark: { neutral: "rgb(125, 184, 217)", error: "rgb(250, 7, 21)", ok: "rgb(14, 181, 150)", warn: "rgb(224, 164, 0)" },
};
const VIEWPORTS = { desktop: { width: 1280, height: 800 }, m390: { width: 390, height: 780 }, m360: { width: 360, height: 740 } };

// Go to a sidebar view. Below 860 px the sidebar is an off-canvas drawer, so open it first.
async function goTo(page, navSelector) {
  if (await page.isVisible("#sidebar-toggle")) await page.click("#sidebar-toggle");
  await page.click(navSelector);
}

// Module scenes beyond the connectors one: how to reach each and where it is drawn. A scene is
// only downloaded once its surface is shown (agentes.js paints on un-hide), which is checked too.
const MODULE_SURFACES = [
  { name: "alertas", open: (page) => page.click("#alerts-btn"), host: "#alert-preferences-modal", card: ".modal-card" },
  { name: "reportes", open: (page) => page.click("#reports-btn"), host: "#report-preferences-modal", card: ".modal-card" },
  // shown on its own once the store's metrics load, so there is no "before it is shown" moment to check
  { name: "dashboard", open: async () => {}, host: "#metrics-empty", card: ".agents-empty-frame", lazy: false },
  { name: "perfil", open: (page) => goTo(page, "#nav-profile"), host: "#profile-panel", card: ".store-panel-header" },
  { name: "auditoria", open: (page) => page.click("#audit-log-btn"), host: "#audit-log-modal", card: ".modal-card" },
  {
    name: "equipo", open: (page) => goTo(page, "#nav-members"), host: "#members-panel", card: ".store-panel-header",
    extra: async (page, tag) => {
      const drawn = (selector) => page.waitForSelector(selector, { timeout: 10000 }).then(() => true, () => false);
      check(`[${tag}] member rows carry their role chip`, await drawn("#members-list .member-chip svg"));
      const rows = await page.evaluate(() => ({
        rows: document.querySelectorAll("#members-list .member-row").length,
        chips: document.querySelectorAll("#members-list .member-chip svg").length,
        first: (document.querySelector("#members-list .member-chip") || { dataset: {} }).dataset.agentKey || "",
      }));
      check(`[${tag}] one chip per member, owner drawn as owner`, rows.rows > 0 && rows.rows === rows.chips && rows.first.startsWith("chips:owner:"), JSON.stringify(rows));
      await goTo(page, "#nav-profile");
      check(`[${tag}] Perfil's team summary shows role chips`, await drawn("#profile-team-summary .team-chip svg"));
    },
  },
];

const problems = [];
let total = 0;
function check(name, ok, detail = "") {
  total += 1;
  if (!ok) problems.push(`${name} ${detail}`);
  console.log(`${ok ? "PASS" : "FAIL"}  ${name}${detail ? "  — " + detail : ""}`);
}

async function post(url, body, token) {
  const res = await fetch(API_URL + url, {
    method: "POST",
    headers: { "Content-Type": "application/json", ...(token ? { Authorization: `Bearer ${token}` } : {}) },
    body: JSON.stringify(body),
  });
  if (!res.ok) throw new Error(`POST ${url} -> ${res.status} ${await res.text()}`);
  return res.json();
}

async function put(url, body, token) {
  const res = await fetch(API_URL + url, {
    method: "PUT",
    headers: { "Content-Type": "application/json", Authorization: `Bearer ${token}` },
    body: JSON.stringify(body),
  });
  if (!res.ok) throw new Error(`PUT ${url} -> ${res.status} ${await res.text()}`);
  return res.json();
}

async function open(browser, { theme, viewport, tokens, reducedMotion, role }) {
  // Service workers stay blocked so a cached shell from an earlier run can't hide a regression.
  const context = await browser.newContext({ viewport, reducedMotion: reducedMotion || "no-preference", serviceWorkers: "block" });
  await context.addInitScript(({ theme, tokens }) => {
    localStorage.setItem("aramal_theme", theme);
    localStorage.setItem("escal_token", tokens.access_token);
    localStorage.setItem("escal_refresh_token", tokens.refresh_token);
  }, { theme, tokens });
  const page = await context.newPage();
  const errors = [];
  page.on("pageerror", (e) => errors.push(`pageerror: ${e.message}`));
  page.on("console", (m) => { if (m.type() === "error") errors.push(`console: ${m.text()}`); });
  const files = [];
  page.on("response", (r) => { if (r.url().includes("/agentes/")) files.push({ name: r.url().split("/agentes/")[1], status: r.status() }); });
  if (role) {
    await page.route("**/auth/me", async (route) => {
      const res = await route.fetch();
      await route.fulfill({ response: res, json: { ...(await res.json()), role } });
    });
  }
  return { context, page, errors, files };
}

async function shot(page, name, options = {}) {
  if (SHOTS_DIR) await page.screenshot({ path: path.join(SHOTS_DIR, name), ...options });
}

(async () => {
  const browser = await chromium.launch();
  const account = { account_name: "Agentes QA", email: `agentes-qa-${Date.now()}@example.com`, password: "Aramal-QA-2026!xQ7" };
  const tokens = await post("/auth/register", account);
  console.log(`Registered ${account.email} on ${API_URL}`);

  // 1) Empty dashboard scene: both themes, every viewport.
  for (const theme of ["light", "dark"]) {
    for (const [vp, viewport] of Object.entries(VIEWPORTS)) {
      const { context, page, errors, files } = await open(browser, { theme, viewport, tokens });
      await page.goto(APP);
      await page.waitForSelector("#empty-state:not([hidden]) .pxa-scene svg", { timeout: 10000 });
      await page.waitForSelector("#account-chip svg", { timeout: 10000 });
      const m = await page.evaluate(() => {
        const scene = document.querySelector("#empty-state .pxa-scene");
        const strip = getComputedStyle(scene.querySelector(".pxa-st"));
        const box = scene.getBoundingClientRect();
        return {
          name: strip.animationName, timing: strip.animationTimingFunction,
          w: box.width, h: box.height,
          scrollW: document.documentElement.scrollWidth, innerW: window.innerWidth,
          outline: getComputedStyle(scene.querySelector("path.c75")).fill,
        };
      });
      const tag = `${theme}/${vp}`;
      check(`[${tag}] scene animates with steps()`, m.name === "pxa-strip" && m.timing.startsWith("steps(4"), `${m.name} ${m.timing}`);
      check(`[${tag}] no horizontal scroll`, m.scrollW <= m.innerW, `${m.scrollW}/${m.innerW}`);
      check(`[${tag}] scene keeps its 48:30 ratio`, Math.abs(m.w / m.h - 1.6) < 0.02, `${Math.round(m.w)}x${Math.round(m.h)}`);
      check(`[${tag}] theme colors applied`, m.outline === OUTLINE[theme], m.outline);
      check(`[${tag}] no console errors`, errors.length === 0, errors.join(" | "));
      if (vp === "desktop") {
        check(`[${tag}] agent files all load`, files.length > 0 && files.every((f) => f.status === 200), files.map((f) => f.name).join(", "));
      }
      await shot(page, `empty-${theme}-${vp}.png`);
      await context.close();
    }
  }

  // 2) Pause button.
  {
    const { context, page } = await open(browser, { theme: "light", viewport: VIEWPORTS.desktop, tokens });
    await page.goto(APP);
    await page.waitForSelector("#empty-state .pxa-st");
    const read = () => page.evaluate(() => ({
      play: getComputedStyle(document.querySelector("#empty-state .pxa-st")).animationPlayState,
      pressed: document.getElementById("agents-pause").getAttribute("aria-pressed"),
      stored: localStorage.getItem("aramal_agents_paused"),
    }));
    let s = await read();
    check("pause: starts running", s.play === "running" && s.pressed === "false", JSON.stringify(s));
    await page.click("#agents-pause");
    s = await read();
    check("pause: click pauses", s.play === "paused" && s.pressed === "true" && s.stored === "1", JSON.stringify(s));
    await page.reload();
    await page.waitForSelector("#empty-state .pxa-st");
    s = await read();
    check("pause: survives a reload", s.play === "paused" && s.pressed === "true", JSON.stringify(s));
    await page.click("#agents-pause");
    s = await read();
    check("pause: click resumes", s.play === "running" && s.pressed === "false" && s.stored === "0", JSON.stringify(s));
    await context.close();
  }

  // 3) prefers-reduced-motion.
  {
    const { context, page } = await open(browser, { theme: "light", viewport: VIEWPORTS.desktop, tokens, reducedMotion: "reduce" });
    await page.goto(APP);
    await page.waitForSelector("#empty-state .pxa-st");
    const r = await page.evaluate(() => {
      const strip = getComputedStyle(document.querySelector("#empty-state .pxa-st"));
      return { animation: strip.animationName, transform: strip.transform, pause: getComputedStyle(document.getElementById("agents-pause")).display };
    });
    check("reduced motion: animation off", r.animation === "none", r.animation);
    check("reduced motion: first frame stays (no transform)", r.transform === "none", r.transform);
    check("reduced motion: pause button hidden", r.pause === "none", r.pause);
    await context.close();
  }

  // 4) Role portraits: chip in the topbar and bust in Perfil.
  for (const role of ["owner", "admin", "viewer"]) {
    for (const theme of ["light", "dark"]) {
      const { context, page, errors } = await open(browser, { theme, viewport: VIEWPORTS.desktop, tokens, role: role === "owner" ? null : role });
      await page.goto(APP);
      await page.waitForSelector("#account-chip svg");
      await page.click("#nav-profile");
      await page.waitForSelector("#profile-bust svg");
      const keys = await page.evaluate(() => ({
        chip: document.getElementById("account-chip").dataset.agentKey,
        bust: document.getElementById("profile-bust").dataset.agentKey,
      }));
      check(`[${role}/${theme}] chip and bust match the role`, keys.chip.startsWith(`chips:${role}:`) && keys.bust.startsWith(`busts:${role}:`), `${keys.chip} | ${keys.bust}`);
      check(`[${role}/${theme}] no console errors`, errors.length === 0, errors.join(" | "));
      await shot(page, `perfil-${role}-${theme}.png`, { clip: { x: 0, y: 0, width: 1280, height: 330 } });
      await context.close();
    }
  }

  // 5) With a store, the connectors widget carries the module head.
  await post("/stores", { name: "Tienda QA", platform: "shopify", currency: "ARS" }, tokens.access_token);
  for (const theme of ["light", "dark"]) {
    const { context, page, errors } = await open(browser, { theme, viewport: VIEWPORTS.desktop, tokens });
    await page.goto(APP);
    await page.waitForSelector("[data-agent-head] svg", { timeout: 10000 }).catch(() => {});
    check(`[store/${theme}] connectors widget head drawn`, await page.evaluate(() => !!document.querySelector("[data-agent-head] svg")));
    check(`[store/${theme}] empty state hidden`, await page.evaluate(() => document.getElementById("empty-state").hidden));
    check(`[store/${theme}] no console errors`, errors.length === 0, errors.join(" | "));
    await shot(page, `store-${theme}.png`);
    await context.close();
  }

  // 5b) Module scenes: lazy, animated, themed, and inside their container on desktop and at 360 px.
  for (const surface of MODULE_SURFACES) {
    for (const theme of ["light", "dark"]) {
      for (const vp of ["desktop", "m360"]) {
        const { context, page, errors, files } = await open(browser, { theme, viewport: VIEWPORTS[vp], tokens });
        await page.goto(APP);
        await page.waitForSelector("#store-panel:not([hidden])", { timeout: 10000 });
        const tag = `${surface.name}/${theme}/${vp}`;
        const file = `escenas/${surface.name}.json`;
        if (surface.lazy !== false) {
          check(`[${tag}] scene is not downloaded before it is shown`, !files.some((f) => f.name === file), files.map((f) => f.name).join(", "));
        }
        await surface.open(page);
        await page.waitForSelector(`${surface.host} .pxa-scene svg`, { timeout: 10000 });
        const m = await page.evaluate(({ host, card }) => {
          const scene = document.querySelector(`${host} .pxa-scene`);
          const strip = getComputedStyle(scene.querySelector(".pxa-st"));
          const box = scene.getBoundingClientRect();
          const cardBox = document.querySelector(`${host} ${card || ""}`).getBoundingClientRect();
          return {
            name: strip.animationName, timing: strip.animationTimingFunction, playing: strip.animationPlayState,
            inside: box.left >= cardBox.left - 0.5 && box.right <= cardBox.right + 0.5 && box.width > 40 && box.height > 20,
            scrollW: document.documentElement.scrollWidth, innerW: window.innerWidth,
            outline: getComputedStyle(scene.querySelector("path.c75")).fill,
          };
        }, { host: surface.host, card: surface.card });
        check(`[${tag}] scene animates with steps()`, m.name === "pxa-strip" && /^steps\(\d/.test(m.timing) && m.playing === "running", `${m.name} ${m.timing} ${m.playing}`);
        check(`[${tag}] scene sits inside its container`, m.inside);
        check(`[${tag}] no horizontal scroll`, m.scrollW <= m.innerW, `${m.scrollW}/${m.innerW}`);
        check(`[${tag}] theme colors applied`, m.outline === OUTLINE[theme], m.outline);
        await shot(page, `module-${surface.name}-${theme}-${vp}.png`);
        if (surface.extra) await surface.extra(page, tag);
        check(`[${tag}] no console errors`, errors.length === 0, errors.join(" | "));
        await context.close();
      }
    }
  }

  // 6) Store role: GET /stores carries the effective role, and the topbar chip follows it on
  // the Dashboard while Equipo/Perfil keep showing the account role. There is no second
  // user to hold a real per-store override here, so the list response is rewritten.
  {
    const listed = await (await fetch(`${API_URL}/stores`, { headers: { Authorization: `Bearer ${tokens.access_token}` } })).json();
    check("API: GET /stores includes effective_role", listed.length > 0 && listed.every((s) => s.effective_role === "owner"), JSON.stringify(listed.map((s) => s.effective_role)));

    const { context, page, errors } = await open(browser, { theme: "light", viewport: VIEWPORTS.desktop, tokens });
    await page.route("**/stores", async (route) => {
      const res = await route.fetch();
      await route.fulfill({ response: res, json: (await res.json()).map((s) => ({ ...s, effective_role: "viewer" })) });
    });
    const chipIs = (role) => page.waitForFunction(
      (r) => (document.getElementById("account-chip").dataset.agentKey || "").startsWith(`chips:${r}:`), role, { timeout: 8000 },
    ).then(() => true, () => false);
    await page.goto(APP);
    check("store role: chip on the Dashboard shows the store role", await chipIs("viewer"));
    await page.click("#nav-profile");
    check("store role: chip in Perfil shows the account role", await chipIs("owner"));
    await page.click("#nav-dashboard");
    check("store role: chip is back to the store role on the Dashboard", await chipIs("viewer"));
    check("store role: no console errors", errors.length === 0, errors.join(" | "));
    await context.close();
  }


  // 7) Login welcome agent (logged out).
  {
    const openLogin = async ({ viewport = VIEWPORTS.desktop, visited = false, theme = "light", reducedMotion = "no-preference", tokens: bad = null } = {}) => {
      const context = await browser.newContext({ viewport, reducedMotion, serviceWorkers: "block" });
      await context.addInitScript(({ visited, theme, bad }) => {
        localStorage.setItem("aramal_theme", theme);
        if (visited) localStorage.setItem("aramal_ya_ingreso", "1");
        if (bad) { localStorage.setItem("escal_token", bad); localStorage.setItem("escal_refresh_token", bad); }
      }, { visited, theme, bad });
      const page = await context.newPage();
      const errors = [];
      page.on("pageerror", (e) => errors.push(`pageerror: ${e.message}`));
      page.on("console", (m) => { if (m.type() === "error" && !/status of 40[13]|status of 429/.test(m.text())) errors.push(`console: ${m.text()}`); });
      await page.goto(APP);
      return { context, page, errors };
    };
    const sceneIs = (page, name) => page.waitForFunction((n) => document.getElementById("auth-mascot").dataset.agentScene === n, name, { timeout: 4000 }).then(() => true, () => false);
    const painted = (page) => page.waitForSelector("#auth-mascot svg", { timeout: 8000 }).then(() => true, () => false);

    // first visit
    {
      const { context, page, errors } = await openLogin();
      check("[login agent] a first visit is drawn", await painted(page));
      check("[login agent] a first visit gets the invitation (scene, bubble, ring on the tab)",
        (await sceneIs(page, "login-invita")) && (await page.isVisible("#auth-invite")) &&
        (await page.evaluate(() => document.getElementById("tab-register").classList.contains("agents-invite-hint"))));
      check("[login agent] the invitation is headed by Ross's name and says what to do", (await page.textContent("#auth-invite .ross-who")) === "Ross" &&
        /Primera vez/.test(await page.textContent("#auth-invite")) && /Soy Ross/.test(await page.getAttribute("#auth-invite", "aria-label")));
      await page.click("#auth-invite");
      check("[login agent] the invitation opens the registration tab", (await page.isVisible("#register-form")) && !(await page.isVisible("#auth-invite")));
      check("[login agent] no console errors on a first visit", errors.length === 0, errors.join(" | "));
      await context.close();
    }
    // returning visitor: password, failure, registration strength
    {
      const { context, page } = await openLogin({ visited: true });
      await painted(page);
      check("[login agent] a returning visitor sees it at rest, with no bubble", (await sceneIs(page, "login-reposo")) && !(await page.isVisible("#auth-invite")));
      await page.focus("#login-password");
      check("[login agent] focusing the password: it covers its eyes", await sceneIs(page, "login-clave"));
      await page.evaluate(() => document.getElementById("login-password").blur());
      check("[login agent] leaving the password: back to rest", await sceneIs(page, "login-reposo"));
      await page.fill("#login-email", "nadie@example.com");
      await page.fill("#login-password", "mala-clave-123");
      await page.click('#login-form button[type="submit"]');
      check("[login agent] a failed login: it shakes its head and the message shows", (await sceneIs(page, "login-error")) && (await page.isVisible("#auth-error")));
      await page.fill("#login-email", "otro@example.com");
      check("[login agent] editing after the failure: back to rest", await sceneIs(page, "login-reposo"));

      await page.click("#tab-register");
      check("[login agent] registration tab: at rest", await sceneIs(page, "login-reposo"));
      const type = async (value) => { await page.fill("#register-password", ""); await page.locator("#register-password").pressSequentially(value); };
      await type("abc123");
      check("[login agent] a very weak password worries it", await sceneIs(page, "login-preocupada"));
      await type("aramal12345");
      check("[login agent] an acceptable password: it rests", await sceneIs(page, "login-reposo"));
      await type("Aramal-2026-Xq!7");
      check("[login agent] a strong password: thumbs up", await sceneIs(page, "login-aprueba"));
      await page.fill("#register-password", "");
      check("[login agent] an emptied password: back to rest", await sceneIs(page, "login-reposo"));
      await context.close();
    }
    // registration success: the celebration is seen before the dashboard (and skipped with reduced motion)
    const register = async (reducedMotion) => {
      const { context, page } = await openLogin({ visited: true, reducedMotion });
      await painted(page);
      await page.click("#tab-register");
      await page.fill("#register-account-name", "Bienvenida QA");
      await page.fill("#register-email", `bienvenida-${reducedMotion}-${Date.now()}@example.com`);
      await page.fill("#register-password", "Aramal-2026-Xq!7");
      const start = Date.now();
      await page.click('#register-form button[type="submit"]');
      const celebrated = await sceneIs(page, "login-festeja");
      await page.waitForSelector("#dashboard-view:not([hidden])", { timeout: 10000 });
      const ms = Date.now() - start;
      const remembered = await page.evaluate(() => localStorage.getItem("aramal_ya_ingreso") === "1");
      await context.close();
      return { celebrated, ms, remembered };
    };
    const normal = await register("no-preference");
    check("[login agent] a new account: it celebrates", normal.celebrated);
    check("[login agent] the celebration is seen before the dashboard", normal.ms >= 1150, `${normal.ms} ms`);
    check("[login agent] the first ingress is remembered", normal.remembered);
    const reduced = await register("reduce");
    check("[login agent] with reduced motion the dashboard does not wait for the celebration", reduced.ms < normal.ms - 700, `${reduced.ms} ms vs ${normal.ms} ms`);

    // an expired session
    {
      const { context, page } = await openLogin({ visited: true, tokens: "token-vencido" });
      const message = await page.waitForSelector("#auth-error:not([hidden])", { timeout: 10000 }).then(() => page.textContent("#auth-error"), () => "");
      check("[login agent] an expired session shows the message", /sesión expiró/.test(message), message);
      check("[login agent] an expired session worries it (it does not shake its head)", await sceneIs(page, "login-preocupada"));
      await context.close();
    }
    // phone: nothing clipped or overflowing, both themes drawn
    for (const theme of ["light", "dark"]) {
      const { context, page } = await openLogin({ viewport: VIEWPORTS.m360, theme });
      await painted(page);
      await sceneIs(page, "login-invita");
      const m = await page.evaluate(() => {
        const rect = (sel) => document.querySelector(sel).getBoundingClientRect();
        const agent = rect("#auth-mascot"), bubble = rect("#auth-invite"), side = rect(".auth-formside");
        return {
          scrollW: document.documentElement.scrollWidth, innerW: window.innerWidth,
          clipped: agent.top < side.top - 0.5,
          bubbleInside: bubble.left >= 0 && bubble.right <= window.innerWidth,
          // the head spans the first 15 of the scene's 22 columns
          clearOfFace: bubble.left >= agent.left + (agent.width * 15) / 22 - 0.5,
          stripe: getComputedStyle(document.getElementById("auth-invite")).borderLeftColor,
          outline: getComputedStyle(document.querySelector("#auth-mascot path.c75")).fill,
        };
      });
      check(`[login agent/${theme}/m360] no horizontal scroll`, m.scrollW <= m.innerW, `${m.scrollW}/${m.innerW}`);
      check(`[login agent/${theme}/m360] the agent is not clipped by the form side`, !m.clipped);
      check(`[login agent/${theme}/m360] the bubble stays inside the screen`, m.bubbleInside);
      check(`[login agent/${theme}/m360] the bubble stays clear of the agent's face`, m.clearOfFace);
      check(`[login agent/${theme}/m360] the bubble's stripe is the neutral greeting color`, m.stripe === STRIPE[theme].neutral, m.stripe);
      check(`[login agent/${theme}/m360] theme colors applied`, m.outline === OUTLINE[theme], m.outline);
      await shot(page, `login-agent-${theme}-m360.png`);
      await context.close();
    }
  }

  // 8) App mascot: True ROAS mood, loading block, error toast.
  {
    const seeded = await post("/auth/register", { account_name: "Mascota QA", email: `mascota-qa-${Date.now()}@example.com`, password: "Aramal-QA-2026!xQ7" });
    const store = await post("/stores", { name: "Local QA", platform: "shopify", currency: "ARS" }, seeded.access_token);
    {
      const { context, page } = await open(browser, { theme: "light", viewport: VIEWPORTS.desktop, tokens: seeded });
      await page.goto(APP);
      await page.waitForSelector("#store-panel:not([hidden])");
      await page.click("#seed-btn");
      await page.waitForFunction(() => document.getElementById("metrics-empty").hidden === true, null, { timeout: 30000 });
      await context.close();
    }
    const alertPrefs = (roas) => put(`/stores/${store.id}/alert-preferences`, { enabled: false, cac_threshold: null, roas_threshold: roas, roas_days_n: 3 }, seeded.access_token);
    const mood = (page) => page.evaluate(() => {
      const art = document.querySelector(".stat-hero .mascot-mood-art"), note = document.querySelector(".stat-hero .mascot-mood-note");
      return art && note ? {
        scene: art.dataset.agentScene, drawn: !!art.querySelector("svg"), text: note.textContent, low: note.classList.contains("low"),
        who: (note.querySelector(".ross-who") || {}).textContent, arrow: (note.querySelector(".ross-arrow") || {}).textContent, stripe: getComputedStyle(note).borderLeftColor,
      } : null;
    });

    // True ROAS mood: above / below the minimum, on desktop and phone, in both themes
    for (const [roas, scene, phrase] of [[0.5, "mascota-festeja", "Por encima de tu mínimo (0,5x)"], [50, "mascota-preocupada", "Por debajo de tu mínimo (50,0x)"]]) {
      await alertPrefs(roas);
      for (const [vp, theme] of [["desktop", "light"], ["m360", "dark"]]) {
        const { context, page, errors } = await open(browser, { theme, viewport: VIEWPORTS[vp], tokens: seeded });
        await page.goto(APP);
        await page.waitForSelector(".stat-hero .mascot-mood-art svg", { timeout: 15000 }).catch(() => {});
        const m = await mood(page);
        const tag = `mood ${roas}/${vp}/${theme}`;
        check(`[${tag}] the mascot stands on the True ROAS card with the right pose`, !!m && m.scene === scene && m.drawn, JSON.stringify(m));
        check(`[${tag}] a sentence says the same in words`, !!m && m.text.includes(phrase), m && m.text);
        check(`[${tag}] Ross's label heads the box and the stripe is ${roas === 0.5 ? "green" : "amber (not red)"}`,
          !!m && m.who === "Ross" && m.arrow === (roas === 0.5 ? "▲" : "▼") && m.stripe === STRIPE[theme][roas === 0.5 ? "ok" : "warn"], JSON.stringify(m));
        const box = await page.evaluate(() => {
          const card = document.querySelector(".stat-hero").getBoundingClientRect(), art = document.querySelector(".stat-hero .mascot-mood-art").getBoundingClientRect();
          return { inside: art.left >= card.left && art.right <= card.right && art.top >= card.top - 1 && art.bottom <= card.bottom + 1, scrollW: document.documentElement.scrollWidth, innerW: window.innerWidth };
        });
        check(`[${tag}] it stays inside the card, with no horizontal scroll`, box.inside && box.scrollW <= box.innerW, JSON.stringify(box));
        check(`[${tag}] no console errors`, errors.length === 0, errors.join(" | "));
        if (vp === "desktop") await shot(page, `mood-${scene}.png`, { clip: { x: 220, y: 60, width: 760, height: 320 } });
        await context.close();
      }
    }
    // a new minimum saved in Alertas changes the pose without reloading
    {
      await alertPrefs(50);
      const { context, page } = await open(browser, { theme: "light", viewport: VIEWPORTS.desktop, tokens: seeded });
      await page.goto(APP);
      await page.waitForSelector(".stat-hero .mascot-mood-art svg", { timeout: 15000 });
      await page.click("#alerts-btn");
      await page.fill("#alert-roas-threshold", "0.5");
      await page.click('#alert-preferences-form button[type="submit"]');
      const changed = await page.waitForFunction(() => { const a = document.querySelector(".stat-hero .mascot-mood-art"); return a && a.dataset.agentScene === "mascota-festeja"; }, null, { timeout: 5000 }).then(() => true, () => false);
      check("[mood] saving a new minimum in Alertas changes the pose without reloading", changed);
      await context.close();
    }

    // loading block: only when the numbers take a moment
    {
      const { context, page } = await open(browser, { theme: "light", viewport: VIEWPORTS.desktop, tokens: seeded });
      await page.route(/\/metrics\/(summary|daily)\?/, async (route) => { await new Promise((r) => setTimeout(r, 1800)); await route.continue(); });
      await page.goto(APP);
      const shown = await page.waitForSelector("#chart-container .mascot-loading svg", { timeout: 6000 }).then(() => true, () => false);
      check("[loading] a slow answer shows the mascot typing on the laptop", shown);
      check("[loading] the block says it is Ross who is bringing the numbers", shown && /Ross está trayendo tus números/.test(await page.textContent("#chart-container .mascot-loading")));
      if (shown) await shot(page, "loading.png", { clip: { x: 220, y: 380, width: 1060, height: 260 } });
      const gone = await page.waitForSelector("#chart-container .mascot-loading", { state: "detached", timeout: 8000 }).then(() => true, () => false);
      check("[loading] it disappears once the numbers arrive", gone);
      await context.close();
    }
    {
      const { context, page } = await open(browser, { theme: "light", viewport: VIEWPORTS.desktop, tokens: seeded });
      await page.goto(APP);
      await page.waitForSelector("#store-panel:not([hidden])");
      await page.waitForTimeout(1200);
      check("[loading] a fast answer never flashes it", (await page.locator(".mascot-loading").count()) === 0);
      await context.close();
    }
    {
      const { context, page } = await open(browser, { theme: "light", viewport: VIEWPORTS.desktop, tokens: seeded });
      await page.route(/\/metrics\/summary\?/, async (route) => { await new Promise((r) => setTimeout(r, 900)); await route.abort(); });
      await page.goto(APP);
      const failed = await page.waitForFunction(() => /No pudimos traer tus números/.test((document.getElementById("chart-container") || {}).textContent || ""), null, { timeout: 8000 }).then(() => true, () => false);
      check("[loading] if the numbers fail, the block is replaced by a message", failed);
      await context.close();
    }

    // error toast instead of alert()
    for (const [vp, theme] of [["desktop", "light"], ["m360", "dark"]]) {
      const { context, page } = await open(browser, { theme, viewport: VIEWPORTS[vp], tokens: seeded });
      let dialogs = 0;
      page.on("dialog", (d) => { dialogs += 1; d.dismiss(); });
      await page.route(/\/stores\/[^/]+\/products$/, (route) => route.abort());
      await page.goto(APP);
      await page.waitForSelector("#store-panel:not([hidden])");
      await page.click("#seed-btn");
      const toast = await page.waitForSelector("#mascot-toast:not([hidden]) svg", { timeout: 8000 }).then(() => true, () => false);
      const tag = `toast/${vp}/${theme}`;
      check(`[${tag}] a failed action shows the mascot's toast`, toast);
      const t = await page.evaluate(() => {
        const box = document.getElementById("mascot-toast");
        const rect = box.getBoundingClientRect();
        const art = box.querySelector(".mascot-toast-art").getBoundingClientRect();
        return { text: box.textContent, role: box.getAttribute("role"), scene: box.querySelector(".mascot-toast-art").dataset.agentScene,
          who: (box.querySelector(".ross-who") || {}).textContent, stripe: getComputedStyle(box).borderLeftColor, standing: Math.abs(art.bottom - rect.top) <= 2,
          inside: rect.left >= 0 && rect.right <= window.innerWidth && rect.bottom <= window.innerHeight, outline: getComputedStyle(box.querySelector("path.c75")).fill };
      });
      check(`[${tag}] it says what failed, in a live region, with the cable pose`, /No se pudo cargar la demo/.test(t.text) && t.role === "alert" && t.scene === "mascota-error", JSON.stringify(t));
      check(`[${tag}] it fits the screen and uses the theme colors`, t.inside && t.outline === OUTLINE[theme], JSON.stringify(t));
      check(`[${tag}] Ross's label heads it, the stripe is red and Ross stands on its top edge`, t.who === "Ross" && t.stripe === STRIPE[theme].error && t.standing, JSON.stringify(t));
      check(`[${tag}] the browser's alert() is not used`, dialogs === 0, `${dialogs} dialogs`);
      if (vp === "desktop") await shot(page, "toast.png", { clip: { x: 760, y: 560, width: 520, height: 240 } });
      await page.click("#mascot-toast .btn");
      check(`[${tag}] Cerrar dismisses it`, !(await page.isVisible("#mascot-toast")));
      await page.click("#seed-btn");
      await page.waitForSelector("#mascot-toast:not([hidden])", { timeout: 8000 });
      await page.keyboard.press("Escape");
      check(`[${tag}] Escape dismisses it`, !(await page.isVisible("#mascot-toast")));
      await context.close();
    }
  }

  // 9) First steps: the card for an account that still has things to set up.
  {
    // Registering is limited to 5 a minute per address: wait for the window instead of failing.
    const fresh = async (label, { store = true } = {}) => {
      const body = { account_name: `${label} QA`, email: `${label.toLowerCase().replace(/\W/g, "-")}-${Date.now()}@example.com`, password: "Aramal-QA-2026!xQ7" };
      let tokensFor;
      for (;;) {
        try {
          tokensFor = await post("/auth/register", body);
          break;
        } catch (err) {
          if (!/ 429 /.test(err.message)) throw err;
          await new Promise((resolve) => setTimeout(resolve, 15000));
        }
      }
      const made = store ? await post("/stores", { name: "Tienda QA", platform: "tiendanube", currency: "ARS" }, tokensFor.access_token) : null;
      return { tokens: tokensFor, store: made };
    };
    const cardState = (page) => page.evaluate(() => {
      const card = document.getElementById("first-steps");
      const rows = Array.from(card.querySelectorAll("li")).map((li) => ({
        title: li.querySelector("strong").textContent, done: li.classList.contains("done"),
        button: li.querySelector("button") ? li.querySelector("button").textContent : null,
        primary: !!li.querySelector("button.btn-primary"),
      }));
      return {
        visible: !card.hidden, heading: (card.querySelector("h3") || {}).textContent || "", rows,
        scene: (card.querySelector(".first-steps-art") || {}).dataset && card.querySelector(".first-steps-art").dataset.agentScene,
        drawn: !!card.querySelector(".first-steps-art svg"),
      };
    });
    const spyClicks = (page) => page.evaluate(() => {
      window.__clicked = [];
      document.addEventListener("click", (event) => window.__clicked.push(event.target.id || event.target.textContent.trim()), true);
    });

    // no store yet: the empty state has its own button, the card stays away
    {
      const { tokens: noStore } = await fresh("Sin tienda", { store: false });
      const { context, page } = await open(browser, { theme: "light", viewport: VIEWPORTS.desktop, tokens: noStore });
      await page.goto(APP);
      await page.waitForSelector("#empty-state:not([hidden])");
      await page.waitForTimeout(600);
      check("[first steps] with no store there is no card (the empty state has its own button)", (await cardState(page)).visible === false);
      await context.close();
    }

    // the whole path, on desktop: every button goes straight to its action, nothing opens by itself
    {
      const { tokens: mine } = await fresh("Primeros pasos");
      const { context, page, errors } = await open(browser, { theme: "light", viewport: VIEWPORTS.desktop, tokens: mine });
      await page.goto(APP);
      await page.waitForSelector("#first-steps:not([hidden]) .first-steps-art svg", { timeout: 15000 });
      let s = await cardState(page);
      check("[first steps] a store with no orders and no alert shows 1 of 3 with Ross drawn", s.heading === "Primeros pasos · 1 de 3" && s.scene === "login-reposo" && s.drawn, JSON.stringify(s));
      check("[first steps] the store is done and the other two have a button; the next one is the primary", s.rows.length === 3 && s.rows[0].done && s.rows[1].button === "Cargar demo" && s.rows[1].primary && s.rows[2].button === "Configurar" && !s.rows[2].primary, JSON.stringify(s.rows));
      check("[first steps] nothing has opened by itself", await page.evaluate(() => ["new-store-modal", "alert-preferences-modal", "report-preferences-modal", "store-members-modal"].every((id) => document.getElementById(id).hidden)));
      await shot(page, "first-steps.png", { clip: { x: 220, y: 60, width: 1060, height: 300 } });
      await spyClicks(page);

      // "Configurar": the alerts form is what opens, in front of the person, with focus inside it
      await page.click("#first-steps li:nth-child(3) button");
      await page.waitForSelector("#alert-preferences-modal:not([hidden])", { timeout: 8000 });
      const focused = await page.evaluate(() => document.activeElement && document.activeElement.id);
      check("[first steps] Configurar opens the alerts form with focus on its first field", focused === "alert-enabled", String(focused));
      check("[first steps] it goes straight there: no other button is pressed for the person", await page.evaluate(() => window.__clicked.length === 1 && !window.__clicked.includes("alerts-btn")), JSON.stringify(await page.evaluate(() => window.__clicked)));
      await page.check("#alert-enabled");
      await page.click('#alert-preferences-form button[type="submit"]');
      await page.waitForFunction(() => document.getElementById("alert-preferences-modal").hidden);
      await page.waitForFunction(() => /2 de 3/.test(document.querySelector("#first-steps h3").textContent), null, { timeout: 5000 });
      s = await cardState(page);
      check("[first steps] saving the alert ticks its step (2 of 3) without reloading", s.rows[2].done && s.rows[2].button === null && s.rows[1].primary, JSON.stringify(s.rows));

      // "Cargar demo": loads on the spot, both buttons show the progress, the card goes away when done
      await page.evaluate(() => (window.__clicked = []));
      await page.click("#first-steps li:nth-child(2) button");
      const progress = await page.evaluate(() => ({ seed: document.getElementById("seed-btn").textContent, guide: document.querySelector("#first-steps li:nth-child(2) button").textContent, disabled: document.getElementById("seed-btn").disabled }));
      check("[first steps] Cargar demo shows the progress in the card and in the header button", progress.seed === "Cargando…" && progress.guide === "Cargando…" && progress.disabled, JSON.stringify(progress));
      await page.waitForFunction(() => document.getElementById("first-steps").hidden === true, null, { timeout: 40000 });
      check("[first steps] with the demo loaded and the alert on, the card is gone and the numbers are there", await page.evaluate(() => document.getElementById("metrics-empty").hidden === true && document.getElementById("seed-btn").textContent === "Cargar datos de demo" && !document.getElementById("seed-btn").disabled));
      check("[first steps] no other button was pressed for the person", await page.evaluate(() => !window.__clicked.includes("seed-btn")), JSON.stringify(await page.evaluate(() => window.__clicked)));
      await page.reload();
      await page.waitForSelector("#store-panel:not([hidden])");
      await page.waitForFunction(() => document.getElementById("metrics-empty").hidden === true, null, { timeout: 15000 });
      await page.waitForTimeout(500);
      check("[first steps] once everything is done it stays away after a reload", (await cardState(page)).visible === false);
      check("[first steps] no console errors", errors.length === 0, errors.join(" | "));
      await context.close();
    }

    // The next cases change nothing in this account (a failed load, a role override, layout checks),
    // except putting the card away, which goes last.
    const { tokens: pending } = await fresh("Guia pendiente");

    // an error while loading the demo is reported by the mascot's toast and the button comes back
    {
      const mine = pending;
      const { context, page } = await open(browser, { theme: "light", viewport: VIEWPORTS.desktop, tokens: mine });
      await page.route(/\/stores\/[^/]+\/products$/, (route) => route.abort());
      await page.goto(APP);
      await page.waitForSelector("#first-steps:not([hidden]) li:nth-child(2) button");
      await page.click("#first-steps li:nth-child(2) button");
      const toast = await page.waitForSelector("#mascot-toast:not([hidden])", { timeout: 8000 }).then(() => true, () => false);
      check("[first steps] a failure while loading the demo shows the mascot's toast", toast && /No se pudo cargar la demo/.test(await page.textContent("#mascot-toast")));
      check("[first steps] the button comes back and the step is still pending", await page.evaluate(() => document.querySelector("#first-steps li:nth-child(2) button").textContent === "Cargar demo" && !document.querySelector("#first-steps li:nth-child(2) button").disabled));
      await context.close();
    }

    // a viewer in the store cannot do any of it, so does not get the card
    {
      const mine = pending;
      const { context, page } = await open(browser, { theme: "light", viewport: VIEWPORTS.desktop, tokens: mine });
      await page.route(/\/stores$/, async (route) => {
        const res = await route.fetch();
        await route.fulfill({ response: res, json: (await res.json()).map((s) => ({ ...s, effective_role: "viewer" })) });
      });
      await page.goto(APP);
      await page.waitForSelector("#store-panel:not([hidden])");
      await page.waitForTimeout(1000);
      check("[first steps] a viewer of the store does not get the card", (await cardState(page)).visible === false);
      await context.close();
    }

    // phone and dark theme: fits, is drawn with the theme colors, nothing overflows
    for (const [vp, theme] of [["m360", "light"], ["m360", "dark"], ["m390", "dark"]]) {
      const mine = pending;
      const { context, page, errors } = await open(browser, { theme, viewport: VIEWPORTS[vp], tokens: mine });
      await page.goto(APP);
      await page.waitForSelector("#first-steps:not([hidden]) .first-steps-art svg", { timeout: 15000 });
      const m = await page.evaluate(() => {
        const card = document.getElementById("first-steps").getBoundingClientRect();
        const inside = Array.from(document.querySelectorAll("#first-steps *")).filter((el) => !el.closest(".pxa")).every((el) => { const r = el.getBoundingClientRect(); return r.right <= card.right + 0.5 && r.left >= card.left - 0.5; });
        return { scrollW: document.documentElement.scrollWidth, innerW: window.innerWidth, inside, outline: getComputedStyle(document.querySelector("#first-steps path.c75")).fill };
      });
      const tag = `first steps/${theme}/${vp}`;
      check(`[${tag}] no horizontal scroll and everything stays inside the card`, m.scrollW <= m.innerW && m.inside, JSON.stringify(m));
      check(`[${tag}] theme colors applied and no console errors`, m.outline === OUTLINE[theme] && errors.length === 0, `${m.outline} ${errors.join(" | ")}`);
      await shot(page, `first-steps-${theme}-${vp}.png`, { fullPage: false });
      await context.close();
    }
    // putting it away is remembered for that person
    {
      const mine = pending;
      const { context, page } = await open(browser, { theme: "light", viewport: VIEWPORTS.desktop, tokens: mine });
      await page.goto(APP);
      await page.waitForSelector("#first-steps:not([hidden]) .first-steps-hide");
      await page.click(".first-steps-hide");
      check("[first steps] Ocultar puts the card away", (await cardState(page)).visible === false);
      await page.reload();
      await page.waitForSelector("#store-panel:not([hidden])");
      await page.waitForTimeout(1000);
      check("[first steps] and it stays away after a reload", (await cardState(page)).visible === false);
      await context.close();
    }

  }

  await browser.close();
  console.log(`\n${total - problems.length}/${total} checks passed`);
  if (problems.length) {
    console.log(`PROBLEMS:\n- ${problems.join("\n- ")}`);
    process.exit(1);
  }
})().catch((err) => {
  console.error(err);
  process.exit(2);
});
